# HPA for AudioProcessor API
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: audio-processor-hpa
  namespace: ml-service
  labels:
    app.kubernetes.io/name: audio-processor-hpa
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/part-of: ml-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: audio-processor
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
---
# HPA for AudioProcessor Workers
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: audio-worker-hpa
  namespace: ml-service
  labels:
    app.kubernetes.io/name: audio-worker-hpa
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/part-of: ml-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: audio-worker
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 20
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 120
      - type: Pods
        value: 5
        periodSeconds: 120
      selectPolicy: Max
---
# HPA for GPU Workers (more conservative scaling)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: audio-gpu-worker-hpa
  namespace: ml-service
  labels:
    app.kubernetes.io/name: audio-gpu-worker-hpa
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/part-of: ml-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: audio-gpu-worker
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 900
      policies:
      - type: Percent
        value: 50
        periodSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 300
      - type: Pods
        value: 1
        periodSeconds: 300
      selectPolicy: Max
